server:
  port: ${PORT}

spring:
  application:
    name: ${NAME}
  rabbitmq:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USER_NAME}
    password: ${REDIS_USER_PASS}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URL}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
